issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/opentelemetry-ebpf-profiler:ref:refs/heads/datadog

claim_pattern:
  event_name: workflow_dispatch
  ref: refs/heads/datadog
  ref_protected: "true"
  job_workflow_ref: DataDog/opentelemetry-ebpf-profiler/.github/workflows/prepare-rebase-on-upstream.yml@refs/heads/datadog

permissions:
  pull_requests: write
